import { Inter } from 'next/font/google';
import 'sanitize.css';

import styles from '@/app/_styles/rootLayout.module.scss';
import RecoilProvider from '@/app/_utile/recoil';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'FFXIV HIKASEN Vtuber Archives',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="jp">
      <body className={styles.rootLayout}>
        <RecoilProvider>{children}</RecoilProvider>
      </body>
    </html>
  );
}
