import { Inter } from 'next/font/google';

import styles from '@/app/_styles/rootLayout.module.scss';
import RecoilProvider from '@/app/_utile/recoil';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'FFXIV HIKASEN Vtuber Archives',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="jp">
      <body className={styles.rootLayout}>
        <section className="ml-5 mr-5 md:ml-0 md:mr-0 md:col-start-2 md:col-end-5">
          <RecoilProvider>{children}</RecoilProvider>
        </section>
      </body>
    </html>
  );
}
